// ZenithVault ABI - Generated from compiled contract
export const ZENITH_VAULT_ABI = [
  // ==================== Read Functions ====================
  {
    inputs: [{ name: "auctionId", type: "uint256" }],
    name: "getAuction",
    outputs: [
      { name: "seller", type: "address" },
      { name: "auctionType", type: "uint8" },
      { name: "reservePrice", type: "uint256" },
      { name: "depositAmount", type: "uint256" },
      { name: "startTime", type: "uint256" },
      { name: "endTime", type: "uint256" },
      { name: "status", type: "uint8" },
      { name: "winner", type: "address" },
      { name: "winningBid", type: "uint64" },
      { name: "paidPrice", type: "uint64" },
      { name: "bidCount", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "auctionId", type: "uint256" }],
    name: "getAuctionItem",
    outputs: [
      { name: "nftContract", type: "address" },
      { name: "tokenId", type: "uint256" },
      { name: "metadataUri", type: "string" },
      { name: "name", type: "string" },
      { name: "description", type: "string" },
      { name: "imageUrl", type: "string" },
      { name: "category", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getActiveAuctions",
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getEndingSoonAuctions",
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "category", type: "string" }],
    name: "getAuctionsByCategory",
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "limit", type: "uint256" }],
    name: "getHotAuctions",
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "offset", type: "uint256" },
      { name: "limit", type: "uint256" },
    ],
    name: "getAuctionsPaginated",
    outputs: [
      { name: "auctionIds", type: "uint256[]" },
      { name: "total", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAuctionCount",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "auctionId", type: "uint256" }],
    name: "getAuctionBidders",
    outputs: [{ name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "auctionId", type: "uint256" }],
    name: "getAuctionTimeRemaining",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "auctionId", type: "uint256" },
      { name: "user", type: "address" },
    ],
    name: "canUserBid",
    outputs: [
      { name: "canBid", type: "bool" },
      { name: "reason", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "auctionId", type: "uint256" }],
    name: "canEndAuction",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCategories",
    outputs: [{ name: "", type: "string[]" }],
    stateMutability: "pure",
    type: "function",
  },
  // User queries
  {
    inputs: [{ name: "user", type: "address" }],
    name: "getUserBidAuctions",
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "user", type: "address" }],
    name: "getUserCreatedAuctions",
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "user", type: "address" }],
    name: "getUserWonAuctions",
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "user", type: "address" }],
    name: "getUserPendingRefunds",
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "auctionId", type: "uint256" },
      { name: "user", type: "address" },
    ],
    name: "getUserBid",
    outputs: [
      { name: "exists", type: "bool" },
      { name: "depositPaid", type: "uint256" },
      { name: "timestamp", type: "uint256" },
      { name: "refunded", type: "bool" },
      { name: "isWinner", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "user", type: "address" }],
    name: "getUserStats",
    outputs: [
      { name: "totalBids", type: "uint256" },
      { name: "totalWins", type: "uint256" },
      { name: "totalCreated", type: "uint256" },
      { name: "totalDeposited", type: "uint256" },
      { name: "pendingRefunds", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  // Platform stats
  {
    inputs: [],
    name: "getPlatformStats",
    outputs: [
      { name: "totalAuctions", type: "uint256" },
      { name: "activeAuctions", type: "uint256" },
      { name: "settledAuctions", type: "uint256" },
      { name: "cancelledAuctions", type: "uint256" },
      { name: "totalBidsPlaced", type: "uint256" },
      { name: "totalVolumeSettled", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "limit", type: "uint256" }],
    name: "getRecentSettledAuctions",
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getContractBalance",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  // Constants
  {
    inputs: [],
    name: "nextAuctionId",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MIN_DURATION",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_DURATION",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MIN_DEPOSIT",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PLATFORM_FEE_BPS",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  // ==================== Write Functions ====================
  {
    inputs: [
      {
        name: "input",
        type: "tuple",
        components: [
          {
            name: "item",
            type: "tuple",
            components: [
              { name: "nftContract", type: "address" },
              { name: "tokenId", type: "uint256" },
              { name: "metadataUri", type: "string" },
              { name: "name", type: "string" },
              { name: "description", type: "string" },
              { name: "imageUrl", type: "string" },
              { name: "category", type: "string" },
            ],
          },
          { name: "auctionType", type: "uint8" },
          { name: "reservePrice", type: "uint256" },
          { name: "depositAmount", type: "uint256" },
          { name: "duration", type: "uint256" },
        ],
      },
    ],
    name: "createAuction",
    outputs: [{ name: "auctionId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "auctionId", type: "uint256" },
      { name: "encryptedBid", type: "bytes32" },
      { name: "proof", type: "bytes" },
    ],
    name: "placeBid",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { name: "auctionId", type: "uint256" },
      { name: "newEncryptedBid", type: "bytes32" },
      { name: "proof", type: "bytes" },
    ],
    name: "increaseBid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "auctionId", type: "uint256" }],
    name: "cancelAuction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "auctionId", type: "uint256" }],
    name: "endAuction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "auctionId", type: "uint256" }],
    name: "requestReveal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "auctionId", type: "uint256" },
      { name: "winningBidValue", type: "uint64" },
      { name: "secondBidValue", type: "uint64" },
      { name: "winnerAddress", type: "address" },
    ],
    name: "settleAuction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "auctionId", type: "uint256" }],
    name: "claimRefund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "auctionId", type: "uint256" }],
    name: "payWinningBid",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  // ==================== Events ====================
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "auctionId", type: "uint256" },
      { indexed: true, name: "seller", type: "address" },
      { indexed: false, name: "itemName", type: "string" },
      { indexed: false, name: "auctionType", type: "uint8" },
      { indexed: false, name: "reservePrice", type: "uint256" },
      { indexed: false, name: "endTime", type: "uint256" },
    ],
    name: "AuctionCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "auctionId", type: "uint256" },
      { indexed: true, name: "bidder", type: "address" },
      { indexed: false, name: "timestamp", type: "uint256" },
    ],
    name: "BidPlaced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "auctionId", type: "uint256" },
      { indexed: true, name: "bidder", type: "address" },
      { indexed: false, name: "timestamp", type: "uint256" },
    ],
    name: "BidIncreased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "auctionId", type: "uint256" }],
    name: "AuctionEnded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "auctionId", type: "uint256" }],
    name: "RevealRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "auctionId", type: "uint256" },
      { indexed: false, name: "winner", type: "address" },
      { indexed: false, name: "winningBid", type: "uint64" },
      { indexed: false, name: "paidPrice", type: "uint64" },
    ],
    name: "AuctionSettled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "auctionId", type: "uint256" }],
    name: "AuctionCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "auctionId", type: "uint256" },
      { indexed: false, name: "bidder", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "DepositRefunded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "auctionId", type: "uint256" },
      { indexed: false, name: "seller", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "WinnerPaid",
    type: "event",
  },
] as const;

// Contract address - Deployed to Sepolia
export const ZENITH_VAULT_ADDRESS = "0x6dd08836B73DC2dd3e294De7f20b18802e282254" as const;
